apiVersion: v1
entries:
  kiam:
  - apiVersion: v1
    appVersion: "3.3"
    created: "2019-08-14T10:33:35.077198976Z"
    description: Integrate AWS IAM with Kubernetes
    digest: 0c773af23eb1885e7bbe1d8b47bcc879f425347bb8bf67b1a0d80b2ba8194734
    engine: gotpl
    home: https://github.com/uswitch/kiam
    keywords:
    - kiam
    - aws
    - iam
    - security
    maintainers:
    - email: Kit_Ewbank@hotmail.com
      name: ewbankkit
    name: kiam
    sources:
    - https://github.com/uswitch/kiam
    urls:
    - kiam-2.5.1.tgz
    version: 2.5.1
generated: "2019-08-14T10:33:35.075047979Z"
