apiVersion: v1
entries:
  nginx:
  - created: "2019-08-13T15:25:00.562989456Z"
    description: A basic NGINX HTTP server
    digest: 411fa59c5907be489b740171cbf3ab027a0eb8e06ae731a4f036e1356e2e4ac7
    home: https://github.com/helm/helm
    keywords:
    - http
    - nginx
    - www
    - web
    kubeVersion: '>=1.2.0'
    maintainers:
    - email: mbutcher@deis.com
      name: technosophos
    name: nginx
    sources:
    - https://hub.docker.com/_/nginx/
    urls:
    - nginx-0.1.0.tgz
    version: 0.1.0
generated: "2019-08-13T15:25:00.56247941Z"
